expose:
  tls:
    certSource: secret
    secret:
      secretName: "harbor.158-160-134-153.sslip.io"
  ingress:
    hosts:
      core: harbor.158-160-134-153.sslip.io
    className: "nginx"
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
      cert-manager.io/acme-challenge-type: http01
externalURL: https://harbor.158-160-134-153.sslip.io
notary:
  enabled: false